version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: task
            MYSQL_USER: root_user
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "9906:3306"
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
    phpmyadmin:
        container_name: php-myadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root_user
            PMA_PASSWORD: root
        depends_on:
            - db
        ports:
            - "8080:80"
